# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c41a1fd467d2f8e0c5bcc133374287adb244bc71bfbf7650055615ad7f2f1eac23faf706b3548b22be0bd426e7fe2342f6da0c3450e3909db87a725d8a5680c

test:
  secret_key_base: 2947e9f732cd086a697c8e5c068a80f1f2c17748001ee10b501574128248ec8a737d30d03ace30b764cdb49bf394b2dcc7c6a53c6aa4fde4bc7d0b91a2e93bab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
